CREATE TABLE roles (
id SERIAL PRIMARY KEY,
name VARCHAR(255) NOT NULL
);

CREATE TABLE users (
id SERIAL PRIMARY KEY,
username VARCHAR(255) NOT NULL,
roleid INT NOT NULL REFERENCES roles(id),
password_hash VARCHAR(255) NOT NULL,
createdat TIMESTAMP NOT NULL
);
